name: 'GitDiff Helm Push'
description: 'Check git diff & Push charts'
inputs:
  chartmuseum-url:
    required: true
  chartmuseum-username:
    required: true
  chartmuseum-password:
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
